id = "rotom"
name = "Rotom"
version = "0.1.0"
schema_version = 1
authors = ["KalaayPT"]
description = "Rotom language support for Zed"
repository = "https://github.com/KalaayPT/rotom-extensions"
languages = ["languages/rotom", "languages/rotom-text-archive"]

[grammars.rotom]
repository = "https://github.com/KalaayPT/tree-sitter-rotom"
rev = "129e909ffaf0a6fbc91738c629f717bf84113f7f"

[lib]
kind = "Rust"

# Do not list built-in "JSON" here — that breaks Zed's core JSON language (grammar name clash).
[language_servers.rotom-lsp]
languages = ["Rotom", "Rotom Text Archive"]
