id = "rotom"
name = "Rotom"
version = "0.1.0"
schema_version = 1
authors = ["KalaayPT"]
description = "Rotom language support for Zed"
repository = "https://github.com/KalaayPT/rotom-extensions"
languages = ["languages/rotom"]

[grammars.rotom]
repository = "https://github.com/KalaayPT/tree-sitter-rotom"
rev = "fbff63816c1597d11c6949618743aa1c2b743f07"

[language_servers.rotom-lsp]
name = "Rotom LSP"
languages = ["Rotom"]
